import { ClerkProvider } from "@clerk/nextjs";
import classNames from "classnames";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Header from "./Components/Header";
import "./globals.css";
import QueryProvider from "./queryProvider";
import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <QueryProvider>
        <html lang="en">
          <body
            className={classNames(
              openSans.className,
              "bg-white text-dark h-screen overflow-hidden"
            )}
          >
            <div className="flex flex-col h-full">
              <Header />
              <Navbar />
              <div className="flex-1 overflow-y-auto flex flex-col">
                <div className="flex-1">{children}</div>
                <Footer />
              </div>
            </div>
          </body>
        </html>
      </QueryProvider>
    </ClerkProvider>
  );
}
