import { ClerkProvider } from "@clerk/nextjs";
import classNames from "classnames";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Header from "./Components/Header";
import Navbar from "./Components/Navbar";
import SetActiveUser from "./Components/SetActiveUser";
import "./globals.css";
import QueryProvider from "./queryProvider";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <QueryProvider>
        <html lang="en">
          <body
            className={classNames(
              openSans.className,
              "bg-white min-h-screen text-dark"
            )}
          >
            <>
              <Header />
              <Navbar />
              <SetActiveUser />
              {children}
            </>
          </body>
        </html>
      </QueryProvider>
    </ClerkProvider>
  );
}
